#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportarEexportar.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Escola")]
	public partial class EscolaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public EscolaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EscolaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EscolaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EscolaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EscolaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EscolaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Alunos> Alunos
		{
			get
			{
				return this.GetTable<Alunos>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alunos")]
	public partial class Alunos
	{
		
		private int _IdAluno;
		
		private string _Nome;
		
		private System.DateTime _DataNascimento;
		
		private string _NomeMae;
		
		private string _NomePai;
		
		private string _Serie;
		
		private string _Turma;
		
		private string _Sala;
		
		public Alunos()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAluno", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int IdAluno
		{
			get
			{
				return this._IdAluno;
			}
			set
			{
				if ((this._IdAluno != value))
				{
					this._IdAluno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this._Nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNascimento", DbType="DateTime NOT NULL")]
		public System.DateTime DataNascimento
		{
			get
			{
				return this._DataNascimento;
			}
			set
			{
				if ((this._DataNascimento != value))
				{
					this._DataNascimento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeMae", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NomeMae
		{
			get
			{
				return this._NomeMae;
			}
			set
			{
				if ((this._NomeMae != value))
				{
					this._NomeMae = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomePai", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NomePai
		{
			get
			{
				return this._NomePai;
			}
			set
			{
				if ((this._NomePai != value))
				{
					this._NomePai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Serie", DbType="VarChar(MAX)")]
		public string Serie
		{
			get
			{
				return this._Serie;
			}
			set
			{
				if ((this._Serie != value))
				{
					this._Serie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Turma", DbType="VarChar(MAX)")]
		public string Turma
		{
			get
			{
				return this._Turma;
			}
			set
			{
				if ((this._Turma != value))
				{
					this._Turma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sala", DbType="VarChar(MAX)")]
		public string Sala
		{
			get
			{
				return this._Sala;
			}
			set
			{
				if ((this._Sala != value))
				{
					this._Sala = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
